version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: chotu-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: chotu
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - chotu-network

  # Backend Server
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: chotu-server
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://admin:password123@mongodb:27017/chotu?authSource=admin
      - CORS_ORIGIN=http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - chotu-network
    volumes:
      - ./server/logs:/app/logs

  # Frontend Client
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: chotu-client
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - server
    networks:
      - chotu-network

volumes:
  mongodb_data:

networks:
  chotu-network:
    driver: bridge